[global]
repo1-path=/tmp/pgbackrest
repo1-retention-full=14
repo1-retention-full-type=time
repo1-host-user=postgres
archive-check=n
process-max=2
log-level-console=info
log-path=/var/log/pgbackrest
log-level-file=debug
start-fast=y
delta=y

[patroni_backup]
pg1-host=172.18.50.151
pg1-host-user=postgres
pg1-database=postgres
pg1-path=/data/patroni
pg1-port=5432

pg2-host=172.18.50.152
pg2-host-user=postgres
pg2-database=postgres
pg2-path=/data/patroni
pg2-port=5432