# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

config.ssh.insert_key = false

  #  worker server 1
  config.vm.define "teamcity-master" do |app|
    app.vm.hostname = "teamcity.ohmylab.lab"
    app.vm.box = "generic/ubuntu2004"
    app.vm.box_check_update  = false
    app.vm.box_version = "3.3.0"
    app.vm.network "private_network", ip: "172.18.50.55"
    
    app.vm.provider :virtualbox do |v|
      v.name    = "teamcity-master"
      v.memory  = 8192
      v.cpus    =  4
    end
  
  app.vm.provision "shell", path: "bootstrap-teamcity-master.sh"
  
  end

end