# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.vm.define "sample-01" do |config|
    config.vm.hostname = "sample-01"
    config.vm.box = "archlinux/archlinux"
    config.vm.box_check_update = false
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.network "private_network", ip: "172.16.55.50"
    
    config.vm.provider :libvirt do |v|
      v.memory = 1024
      v.driver = "qemu"
      v.socket = "/Users/sickboy/.cache/libvirt/libvirt-sock"
      v.uri    = "qemu:///session"
    end
  end
end