# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "kmaster" do |node|
  
    node.vm.box               = "generic/ubuntu2204"
    node.vm.box_check_update  = false
    node.vm.box_version       = "4.2.16"
    node.vm.hostname          = "kmaster.int.ohmylab.io"

    node.vm.network "private_network", ip: "172.16.55.50"
  
    node.vm.provider :virtualbox do |v|
      v.name    = "kmaster"
      v.memory  = 4096
      v.cpus    =  4
    end
  
    node.vm.provision "shell", path: "bootstrap_kmaster.sh"
  
  end


  # Kubernetes Worker Nodes
  NodeCount = 1

  (1..NodeCount).each do |i|

    config.vm.define "kworker0#{i}" do |node|

    node.vm.box               = "generic/ubuntu2204"
    node.vm.box_check_update  = false
    node.vm.box_version       = "4.2.16"
    node.vm.hostname          = "kworker0#{i}.int.ohmylab.io"

    node.vm.network "private_network", ip: "172.16.55.6#{i}"

      node.vm.provider :virtualbox do |v|
        v.name    = "kworker0#{i}"
        v.memory  = 4096
        v.cpus    = 4
      end

      node.vm.provision "shell", path: "bootstrap_kworker.sh"

    end

  end

end
