# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # win test box
  config.vm.define "winsrv" do |srv|
  
    srv.vm.box               = "gusztavvargadr/windows-server-2022-standard"
    srv.vm.box_check_update  = false
    srv.vm.box_version       = "2102.0.2310"
    srv.vm.hostname          = "winsrv"

    srv.vm.network "private_network", virtualbox__intnet: "intnet", auto_config: false

    srv.vm.provider :virtualbox do |v|
      v.name    = "winsrv"
      v.memory  = 8192
      v.cpus    =  4
    end
    
  end

end