---
- name: Fetch and update RKE2 Kubernetes config
  hosts: master_nodes
  become: no
  gather_facts: false
  tasks:
    - name: Ensure local directory exists on localhost
      local_action:
        module: file
        path: ./k8s_configs
        state: directory

    - name: Fetch rke2.yaml from master node to localhost
      fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: ./k8s_configs/rke2_{{ inventory_hostname }}.yaml
        flat: yes
      become: yes

    - name: Replace server address in the rke2.yaml with load balancer address on localhost
      local_action:
        module: replace
        path: ./k8s_configs/rke2_{{ inventory_hostname }}.yaml
        regexp: 'https://127.0.0.1:[0-9]+'
        replace: 'https://{{ hostvars["haproxy"].ansible_host }}:6443'
