---
# join nodes to kubeadm vanilla cluster
- name: Generate join command
  hosts: master_nodes
  become: yes
  tasks:
    - name: Generate join command on master node
      command: kubeadm token create --print-join-command
      register: join_command_raw
      run_once: true

    - name: Set join command as a fact
      set_fact:
        join_command: "{{ join_command_raw.stdout }}"
      run_once: true

    - name: Share the join command with worker nodes
      add_host:
        name: "{{ item }}"
        join_command: "{{ join_command }}"
      loop: "{{ groups['worker_nodes'] }}"
      run_once: true

- name: Wait for API Server to be Reachable
  hosts: worker_nodes
  become: yes
  tasks:
    - name: Wait for API server on master to be reachable
      wait_for:
        host: "{{ hostvars[groups['master_nodes'][0]].ansible_host }}"
        port: 6443
        state: started
        delay: 10
        timeout: 300

- name: Join Worker Nodes to the Cluster
  hosts: worker_nodes
  become: yes
  tasks:
    - name: Join worker node to Kubernetes cluster
      command: "{{ join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf

    - name: Verify worker node has joined the cluster
      shell: "kubectl get nodes --kubeconfig /etc/kubernetes/kubelet.conf"
      register: node_join_result
      failed_when: "'Ready' not in node_join_result.stdout"

    - name: Debug node join result
      debug:
        var: node_join_result.stdout