---
- name: Consolidate SSH Known Hosts
  hosts: localhost
  become: no
  gather_facts: no
  vars:
    hosts_to_consolidate:
      - kmaster1.cluster.local
      - kmaster2.cluster.local
      - kworker.cluster.local
      - kworker
      - kmaster2
      - kmaster1
      - 172.18.50.71
      - 172.18.50.72
      - 172.18.50.61
  tasks:
    - name: Remove existing known_hosts entries for the hosts
      shell: ssh-keygen -R {{ item }}
      loop: "{{ hosts_to_consolidate }}"
      ignore_errors: yes

    - name: Display debug
      debug:
        msg: "{{ hosts_to_consolidate }}"

    - name: Fetch the SSH host key for {{ hosts_to_consolidate[0] }}
      ansible.builtin.command: ssh-keyscan -H {{ hosts_to_consolidate[0] }}
      register: ssh_key
      changed_when: false
      failed_when: ssh_key.rc != 0

    - name: Consolidate hostnames and key into a single entry
      set_fact:
        consolidated_entry: "{{ hosts_to_consolidate | join(',') }} {{ ssh_key.stdout.strip().split(' ', 1)[1] }}"

    - name: Add consolidated known_hosts entry
      known_hosts:
        name: "{{ hosts_to_consolidate[0] }}"
        key: "{{ consolidated_entry }}"
        path: ~/.ssh/known_hosts
        state: present

- name: Test Connectivity and Display Hostnames
  hosts: all
  gather_facts: yes
  tasks:
    - name: Ping the host to test connectivity
      ping:

    - name: Display the system hostname
      debug:
        msg: "The hostname of {{ inventory_hostname }} is {{ ansible_facts.hostname }}. \
        Host is {{ inventory_hostname }} and IP is {{ ansible_host }} but custom hostname is {{ hostname }}"