[global]
repo1-path=/backup/pgbackrestrepo
repo1-retention-full=14
repo1-retention-full-type=time
archive-check=n
process-max=1
log-level-console=info
log-path=/var/log/pgbackrest
log-level-file=debug
start-fast=y
delta=y
compress-level=3

[postgres_sandbox]
pg1-host=172.18.50.151
pg1-host-user=postgres
pg1-database=postgres
pg1-path=/data/patroni
pg1-port=5432

pg2-host=172.18.50.152
pg2-host-user=postgres
pg2-database=postgres
pg2-path=/data/patroni
pg2-port=5432

pg3-host=172.18.50.153
pg3-host-user=postgres
pg3-database=postgres
pg3-path=/data/patroni
pg3-port=5432