---
# tasks file for k8s_rke2_nodes
- name: Create empty dir for RKE2 config
  command: mkdir -p /etc/rancher/rke2

- name: Create RKE2 empty config
  file:
    path: /etc/rancher/rke2/config.yaml
    state: touch
    mode: '0644'

- name: Fetch node token from master node
  fetch:
    src: /var/lib/rancher/rke2/server/node-token
    dest: /tmp/node_token
    flat: yes
  delegate_to: kmaster.cluster.local

- name: Copy node token from control node to worker nodes
  copy:
    src: /tmp/node_token
    dest: /tmp/node_token

- name: Get node token on the worker node
  command: cat /tmp/node_token
  register: node_token
  run_once: true

- name: Populate RKE2 config
  blockinfile:
    path: /etc/rancher/rke2/config.yaml
    block: |
      server: https://{{ master_node_ip }}:9345
      token: "{{ node_token.stdout }}"
      node_name: {{ ansible_hostname }}

- name: Download RKE2 install script
  get_url:
    url: https://get.rke2.io
    dest: /tmp/install-rke2
    mode: '0755'

- name: Bootstrap RKE2 Server
  shell: /tmp/install-rke2
  environment: 
    INSTALL_RKE2_TYPE: "{{ node_role }}"
    INSTALL_RKE2_CHANNEL: "{{ rke2_version }}"
  args:
    executable: /bin/bash

- name: Start RKE2 server service
  systemd:
    name: rke2-server
    enabled: true
    state: started
  when: node_role == "server"

- name: Start RKE2 agent service
  systemd:
    name: rke2-agent
    enabled: true
    state: started
  when: node_role == "agent"