---
# tasks file for k8s_rke2_nodes
- name: Create empty dir for RKE2 config
  command: mkdir -p /etc/rancher/rke2

- name: Create RKE2 empty config
  file:
    path: /etc/rancher/rke2/config.yaml
    state: touch
    mode: '0644'

- name: Populate RKE2 config {{ ansible_host }}
  blockinfile:
    path: /etc/rancher/rke2/config.yaml
    block: |
      server: https://{{ rke2_master_node_ip }}:9345
      token: "{{ node_token }}"
      node_name: {{ inventory_hostname }}
      node-ip: "{{ ansible_host }}"
  when: node_role == "agent"

- name: Populate RKE2 config {{ ansible_host }}
  blockinfile:
    path: /etc/rancher/rke2/config.yaml
    block: |
      server: https://{{ rke2_master_node_ip }}:9345
      token: "{{ node_token }}"
      node_name: {{ inventory_hostname }}
      node-ip: "{{ ansible_host }}"
      cluster-cidr: "{{ cluster_pod_cidr }}"
      service-cidr: "{{ cluster_service_cidr }}"
      cluster-dns: "{{ cluster_dns_ip }}"
      disable-kube-proxy: true
      disable:
        - rke2-canal
        - rke2-kube-proxy
      protect-kernel-defaults: true
  when: node_role == "server"

- name: Download RKE2 install script
  get_url:
    url: https://get.rke2.io
    dest: /tmp/install-rke2
    mode: '0755'

- name: Bootstrap RKE2 node
  shell: /tmp/install-rke2
  environment: 
    INSTALL_RKE2_TYPE: "{{ node_role }}"
    INSTALL_RKE2_CHANNEL: "{{ rke2_version }}"
  args:
    executable: /bin/bash

- name: Start RKE2 server service
  systemd:
    name: rke2-server
    enabled: true
    state: started
  when: node_role == "server"

- name: Start RKE2 agent service
  systemd:
    name: rke2-agent
    enabled: true
    state: started
  when: node_role == "agent"