BOX_IMAGE = "bento/ubuntu-22.04-arm64"
NODE_BOOTSTRAP_SCRIPT = "bootstrap/bootstrap_node.sh"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  (1..2).each do |i|
    config.vm.define "kmaster#{i}" do |kmaster|
      kmaster.vm.hostname = "kmaster#{i}.cluster.local"
      kmaster.vm.network "private_network", ip: "172.18.50.7#{i}"
      kmaster.vm.provision "shell", path: NODE_BOOTSTRAP_SCRIPT
      kmaster.vm.provider "vmware_fusion" do |v|
        v.memory = 4096
        v.cpus = 4
      end
    end
  end

  config.vm.define "kworker" do |worker|
    worker.vm.hostname = "kworker.cluster.local"
    worker.vm.network "private_network", ip: "172.18.50.61"
    worker.vm.provision "shell", path: NODE_BOOTSTRAP_SCRIPT
    worker.vm.provider "vmware_fusion" do |v|
      v.memory = 4096
      v.cpus = 4
    end
  end

  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.synced_folder '.', '/vagrant', disabled: true
    haproxy.vm.hostname = "haproxy.cluster.local"
    haproxy.vm.network "private_network", ip: "172.18.50.100"
    haproxy.vm.provision "shell", path: NODE_BOOTSTRAP_SCRIPT
    haproxy.vm.provider "vmware_fusion" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
end