# BOX_IMAGE = "bento/centos-stream-9-arm64"
BOX_IMAGE = "bento/centos-stream-9"
MASTER_BOOTSTRAP_SCRIPT = "bootstrap/bootstrap_master.sh"
WORKER_BOOTSTRAP_SCRIPT = "bootstrap/bootstrap_worker.sh"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  config.vm.define "master" do |master|
    master.vm.synced_folder ".", "/vagrant", disabled: true
    master.vm.hostname = "master.cluster.local"
    master.vm.network "private_network", ip: "172.18.50.55" 
    master.vm.provision "shell", path: MASTER_BOOTSTRAP_SCRIPT
    master.vm.provision :reload
    master.vm.provision "shell", inline: <<-SHELL
      getenforce
    SHELL
    master.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  (1..2).each do |i|
    config.vm.define "worker0#{i}" do |worker|
      worker.vm.synced_folder ".", "/vagrant", disabled: true
      worker.vm.hostname = "worker0#{i}.cluster.local"
      worker.vm.network "private_network", ip: "172.18.50.6#{i}"
      worker.vm.provision "shell", path: WORKER_BOOTSTRAP_SCRIPT
      worker.vm.provision :reload
      worker.vm.provision "shell", inline: <<-SHELL
        getenforce
      SHELL
      worker.vm.provider "vmware_desktop" do |v|
        v.memory = 2048
        v.cpus = 2
      end
    end
  end
end