BOX_IMAGE = "bento/ubuntu-22.04-arm64"

PG_PROVISION_SCRIPT = "bootstrap/bootstrap_pg.sh"
ETCD_PROVISION_SCRIPT = "bootstrap/bootstrap_etcd.sh"
HAPROXY_PROVISION_SCRIPT = "bootstrap/bootstrap_haproxy.sh"
BACKUPSRV_PROVISION_SCRIPT = "bootstrap/bootstrap_backupsrv.sh"
Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  config.vm.define "etcd" do |etcd|
    etcd.vm.hostname = "etcd"
    etcd.vm.network "private_network", ip: "172.18.50.55" 
    etcd.vm.provision "shell", path: ETCD_PROVISION_SCRIPT
    etcd.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  (1..3).each do |i|
    config.vm.define "pg#{i}" do |pg|
      pg.vm.hostname = "pg#{i}"
      pg.vm.network "private_network", ip: "172.18.50.15#{i}"
      pg.vm.provision "shell", path: PG_PROVISION_SCRIPT
      pg.vm.provider "vmware_desktop" do |v|
        v.memory = 2048
        v.cpus = 2
      end
    end
  end
  
  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.hostname = "haproxy"
    haproxy.vm.network "private_network", ip: "172.18.50.60"
    haproxy.vm.provision "shell", path: HAPROXY_PROVISION_SCRIPT
    haproxy.vm.provider "vmware_desktop" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end

  config.vm.define "backupsrv" do |backupsrv|
    backupsrv.vm.hostname = "backupsrv"
    backupsrv.vm.network "private_network", ip: "172.18.50.160"
    backupsrv.vm.provision "shell", path: BACKUPSRV_PROVISION_SCRIPT
    backupsrv.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
end